services:
  backend:
    build:
      context: .
    container_name: sistema-provas
    image: sistema-provas:latest
    ports:
      - "8080:8080"
    environment:
      - SECRET_HMAC=4f8c2b9a1d6e7f08b3a5c9d4e2f10b7a
volumes:
  pgdata: