services:
  backend:
    build:
      context: .
    container_name: sistema-provas
    ports:
      - "8080:8080"
    ## Desabilitar depends_on se usar banco externo
    depends_on:
      - database
    environment:
      ## Ativar se usar banco externo
      # - SPRING_DATASOURCE_URL=${NEON_URL}
      ## Desativar as 3 linhas se usar banco local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
  database:
    image: postgres:17.7-alpine3.22
    container_name: database-sistem-provas
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: